# Generated by Django 5.1.1 on 2024-09-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_moodentry_carentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='carentry',
            name='car_horsepower',
            field=models.IntegerField(default=471),
        ),
    ]
